# Generated by Django 5.1.3 on 2024-12-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_coordinator',
            new_name='coordenador',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_teacher',
            new_name='professor',
        ),
    ]
